# inputs.conf — Splunk Universal Forwarder
# Installed on: Linux Mint (Target Machine — 192.168.1.133)
# Purpose: Monitor SSH authentication log and forward to Splunk server

[monitor:///var/log/auth.log]
disabled = false
index = main
sourcetype = linux_secure
